### ISSUE TITLE
@imports in the wrong order.

### ISSUE THREAD

**Issue by GrtDev** [BlessCSS/gulp-bless#25] opened 2016-05-02 12:15 UTC
It seems the latest version does the @imports in the wrong order.

@import url('...-blessed1.css');
@import url('...-blessed2.css');

Where blessed2 is actually the start of the original CSS.

I reverted the version to 3.0.0 and there it has the right order.

**Comment by adam-lynch** [comment] 2016-07-02 23:40
There seems to have been a problem in bless itself; see https://github.com/BlessCSS/gulp-bless/issues/22#issuecomment-205973763. I'll close this. Correct me if I'm wrong, but make sure you update this module and its bless dependency to their latest versions.

**Comment by tobbas** [comment] 2016-07-13 08:53
Hi Guys, I´m actually still having this problem. Also had to revert to version gulp-bless 3.0.0.

I see the 3.0.0 version first imports blessed2.css then blessed1.css, which gives me the CSS in correct order.
The gulp-bless 3.1.0 (bless 4.0.4), imports it the other way around.

**Comment by adam-lynch** [comment] 2016-07-30 17:53
@tobbas @peterkr can you give me an example project which reproduces this please?

**Comment by wuifdesign** [comment] 2016-09-28 13:48
having the same problem (3.0.0 works fine)

**Comment by adam-lynch** [comment] 2016-10-09 18:51
@wuifdesign can you give me an example projects which reproduces the problem or submit a pull-request with a test that proves it?

**Comment by wuifdesign** [comment] 2016-10-10 15:21
@adam-lynch Built a small demo: https://github.com/wuifdesign/gulp-bless-test

in the css: 

```
@import url('test-blessed1.css?z=149');
@import url('test-blessed2.css?z=149');
```

But `test-blessed2.css` includes the `.item-1` style and should be loaded first.
So this would be the right order:


```
@import url('test-blessed2.css?z=149');
@import url('test-blessed1.css?z=149');
```

**Comment by alvinlin123** [comment] 2016-10-11 17:47
probably due to lhttps://github.com/BlessCSS/gulp-bless/blob/master/index.js#L133 where `j` is used instead of `newIndex` ? I will see if I can submit a PR soon.

**Comment by adam-lynch** [comment] 2016-10-11 22:23
Thanks @wuifdesign!

Great @alvinlin123. I'll review as soon as I can but I'm a little busy this week.

By the way, this is such a major bug to how this plugin works, people must be relying on this incorrect behaviour. For that reason, when we fix it, should it be a major version bump? I.e. to avoid this breaking user's code.

- Current version: 3.2.0
- Typical bug fix version bump: 3.2.1
- Major / breaking change version bump: 4.0.0

**Comment by alvinlin123** [comment] 2016-11-25 20:06
@adam-lynch I agree with bumping the version, but I have a feeling that maybe we should bump the minor version (i.e. to 3.3.0). Bumping the major version makes it sound like we released new awesome significant feature or that we depend on newer major version of bless  :)

**Comment by adam-lynch** [comment] 2017-06-04 23:11
4.0.0 released with a fix. Thanks for reporting.

**Closed by adam-lynch** 2017-06-04 23:11 UTC
