### ISSUE TITLE
Minified bless files not showing @import rules

### ISSUE THREAD

**Issue by jziggas** [BlessCSS/gulp-bless#40] opened 2017-02-03 01:25 UTC
Hi there,

Am I understanding this correctly? That by default the first blessed file is supposed to @import the rest of them?

If I concat a bunch of CSS sources, then bless it, then minify, I end up with `app.full.min.css` and `app.full.min.part2.css`

Except I don't see an `@import` anywhere in either of the two files, so I'm using [gulp-inject](https://github.com/klei/gulp-inject) to insert link tags back into `index.html`.

But it also appears that the files are in reverse order. That is, `app.full.min.css` and `app.full.min.part2.css` are linked in that order and styling errors appear. But if I link `app.full.min.part2.css` first then everything looks normal.

**Comment by alvinlin123** [comment] 2017-02-03 06:02
Yes, by default @import should be added to the "master" css file. 

Which CSS minifier are you using? I am asking this because I know that clean-css, with default optimization strategies, does not work well with gulp-bless. Like it will actually increase the number of CSS selectors in the split css files.

Do you have any sample project to demonstrate this problem?

**Comment by jziggas** [comment] 2017-02-03 14:23
We're using [gulp-cssmin](https://github.com/chilijung/gulp-cssmin). I could perhaps give you an example function in a private gist. Sorry to be a pain.

**Comment by alvinlin123** [comment] 2017-02-04 12:41
Yea, I tried gulp-cssmin and that's indeed the problem. gulp-cssmin uses cleanCss underneath, which I am aware that it will minify the css a little bit too well. 

To solve the problem of `@import` gone missing do the following:

```javascript
.pipe(gulpBless())
.pipe(gulpCssmin({processImport:false, /*You may also want advance:false */})
```
Also, regarding the ordering, it's probably related to issue #25 .

**Comment by alvinlin123** [comment] 2017-02-04 12:43
I am closing this issue for now as the problem is with other gulp plugin. Feel free to re-open this issue if needed.

**Closed by alvinlin123** 2017-02-04 12:43 UTC

**Comment by jziggas** [comment] 2017-02-07 15:57
Thanks for the help. That doesn't seem to be working either. Do you have another CSS minifier you recommend?

**Comment by alvinlin123** [comment] 2017-02-07 18:58
I usually use `gulp-clean-css` like following: 

```
...
var bless = require('gulp-bless');
var cleanCss     = require('gulp-clean-css');

gulp.task('task', function() {
    ...
       .pipe(bless({imports: true})
       .pipe(cleanCss({
        	advanced: false,
		processImport: false
        }))
        .....
      
});
```

**Comment by jziggas** [comment] 2017-02-07 19:45
Ahhh it is working actually, I forgot I had explicitly added `imports: false` to gulp-bless since it wasn't including them anyway. Once I removed that option, then the two config options you suggested for gulp-css-min seem to have done the trick. Thanks again!

**Comment by quisse** [comment] 2018-07-11 10:39
`processImport` is `inline` since cleanCSS 4.0
